Repository Heptagram-Project/discord-bot, pull requests merged in 2021-04, with the labels that each got.

#25 staged into master
  .DS_Store
  CONTRIBUTING.md
  README.md
Labels: documentation

#52 SYSTEM: Staged into master
  commands/Utilitys/help.js
Labels: SYSTEM

#58 Add joke feature
  commands/Fun/joke.js
Labels: FEATURE, enhancement

#59 SYSTEM: Add joke feature
  commands/Fun/joke.js
Labels: SYSTEM

#62 SYSTEM: Add help command (filtering admin commands as well). (#61)
  commands/Utilitys/help.js
Labels: SYSTEM

#63 Remove deprecated dependancy
  package-lock.json
  package.json
Labels: dependencies

#65 Change to a more stable API and update logic to prevent spamming
  commands/Fun/joke.js
Labels: enhancement

#69 Staged
  commands/COVID/covid-stats.js
  package-lock.json
  package.json
Labels: SYSTEM

#71 New command handler and update joke.js description
  bot.js
  commands/Fun/joke.js
  events/client/ready.js
  events/guild/disconnect.js
  events/guild/error.js
  events/guild/message.js
  events/guild/reconnecting.js
  events/guild/warn.js
  handlers/command_handler.js
  handlers/event_handler.js
Labels: enhancement

#101 Fix lock command
  commands/Moderation/lock.js
Labels: Closed

#111 Improve dbLogging and add channel log
  commands/.DS_Store
  events/client/disconnect.js
  events/client/error.js
  events/client/message.js
  events/client/rateLimit.js
  events/client/ready.js
  events/client/reconnecting.js
  events/client/warn.js
  events/dbLogging.js
  events/guild/channelCreate.js
  events/guild/channelDelete.js
  events/guild/channelPinsUpdate.js
  events/guild/channelUpdate.js
  events/guild/emojiCreate.js
  events/guild/emojiDelete.js
  events/guild/emojiUpdate.js
  events/guild/error.js
  events/guild/guildBanAdd.js
  events/guild/guildBanRemove.js
  events/guild/guildCreate.js
  events/guild/guildDelete.js
  events/guild/guildIntegrationsUpdate.js
  events/guild/guildMemberAdd.js
  events/guild/guildMemberAvailable.js
  events/guild/guildMemberRemove.js
  events/guild/guildMemberSpeaking.js
  events/guild/guildMemberUpdate.js
  events/guild/guildMembersChunk.js
  events/guild/guildUnavailable.js
  events/guild/guildUpdate.js
  events/guild/inviteCreate.js
  events/guild/inviteDelete.js
  events/guild/message.js
  events/guild/messageDelete.js
  events/guild/messageDeleteBulk.js
  events/guild/messageReactionAdd.js
  events/guild/messageReactionRemove.js
  events/guild/messageReactionRemoveAll.js
  events/guild/messageReactionRemoveEmoji.js
  events/guild/messageUpdate.js
  events/guild/presenceUpdate.js
  events/guild/reconnecting.js
  events/guild/roleCreate.js
  events/guild/roleDelete.js
  events/guild/roleUpdate.js
  events/guild/userUpdate.js
  events/guild/voiceStateUpdate.js
  events/guild/warn.js
  events/guild/webhookUpdate.js
  events/shard/shardDisconnect.js
  events/shard/shardError.js
  events/shard/shardReady.js
  events/shard/shardReconnecting.js
  events/shard/shardResume.js
  handlers/event_handler.js
  main.js
  package.json
Labels: SYSTEM
